language: node_js
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules

script: npm run test

before_deploy:
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true
    script: now alias $(now build --public --name burberry-fake-shop-for-study -t=$NOW_TOKEN) $URL_DEV -t=$NOW_TOKEN
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: now alias $(now build --public --name burberry-fake-shop-for-study  -t=$NOW_TOKEN) $URL -t=$NOW_TOKEN
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: now alias $(now build --public --name burberry-fake-shop-for-study  -t=$NOW_TOKEN) $URL_STAGED -t=$NOW_TOKEN
    on:
      branch: feat*
